resources:
- name: concoursesp
  type: git
  source: {uri: https://github.com/gowrisankar22/concoursesp}
jobs:
- name: reconfigure
  plan:
  - get: concoursesp
    trigger: true
  - set_pipeline: concoursesp
    file: concoursesp/ci/pipeline.yml

